sudo: required
services:
  - docker

before_install:
  - docker build -t bujaretemi1998/docker-react -f Dockerfile.dev .

script: 
  - docker run bujaretemi1998/docker-react npm run test -- --coverage
